# Generated by Django 4.0.2 on 2022-03-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articletags_alter_article_options_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletags',
            name='scope',
            field=models.BooleanField(verbose_name='Основной'),
        ),
    ]
