# Generated by Django 4.0.2 on 2022-03-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articletags_scope'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleTags',
            new_name='Scope',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='scope',
            new_name='is_main',
        ),
    ]
