# Generated by Django 4.0.2 on 2022-03-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_teacher_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-group'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
    ]
